### ISSUE TITLE
Large dataset question

### ISSUE THREAD

**Issue by skytguuu** [dgrun/VarID_analysis#1]
Hi,

I met a problem about the large dataset. I have more than 30k cells in my data. I tried to follow the manual of raceid (https://cran.r-project.org/web/packages/RaceID/vignettes/RaceID.html). According to this, I didn't use the normal pipeline ("sc <- clustexp(sc)") and tried the pipeline for large datasets. Followed is my code:

###############
sc <- SCseq(x)
sc <- filterdata(sc,mintotal=1000,CGenes=rownames(x)[grep("^(mt|Rp(l|s)|Gm\\d)",rownames(x))])
expData <- getExpData(sc)
res   <- pruneKnn(expData,no_cores=5)
cl    <- graphCluster(res,pvalue=0.01)
probs <- transitionProbs(res,cl)
noise <- compNoise(expData,res,regNB=FALSE,pvalue=0.01,no_cores=5)
################
When I runned the command: pruneKnn, it reported an warning:
##############
Warning in irlba(A = t(z), nv = pcaComp) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
Warning in irlba(A = t(z), nv = pcaComp) :
  did not converge--results might be invalid!; try increasing work or maxit
###############
I didn't know what's happend of this warning.

Meanwhile, when I tried the compNoise, it reported an error:
#################
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) :
  0 (non-NA) cases
#################
It seems there are some NA in my data. But I don't know how to deal with it?

Could you give me a hand? BTW, whether I did right or not to deal with the large datasets using the pipeline?

Thank you!
Best,
Garen

**Comment by dgrun** [comment]
How many features do you have your data, i.e. what is nrow(expData)? You
could try to reduce the number of singular values to compute by decreasing
the pcaComp argument of pruneKnn, e.g., pcaComp=50.
Perhaps you're filtering too strongly and you are losing too many features.
Try also reducing mintotal, or avoid gene filtering by setting CGenes=NULL.
The reason why the noise calculation doesn't work could be a consequence of
the failure to perform the initial dimensional reduction (lack of
convergence in pruneKnn).

**Comment by dgrun** [comment]
if you provide sample data to reproduce the error this would help.

**Comment by skytguuu** [comment]
Thanks for your quickly reply.  Before I runned the "filterdata" command, I did the filter using seurat tools with the following code:
###############
  s249 = read.csv("SC249.csv",header=TRUE, row.names=1,stringsAsFactors=FALSE)
  s250 = read.csv("SC250.csv",header=TRUE, row.names=1,stringsAsFactors=FALSE)
  my_s249 <- CreateSeuratObject(counts = s249,min.cells = 3, min.features = 200,project = "sc_project")
  my_s250 <- CreateSeuratObject(counts = s250,min.cells = 3, min.features = 200,project = "sc_project")
  my_s249[["percent.mt"]]=PercentageFeatureSet(my_s249, pattern = "^mt.")
  my_s250[["percent.mt"]]=PercentageFeatureSet(my_s250, pattern = "^mt.")
  my_s249 <- subset(my_s249, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 30)
  my_s250 <- subset(my_s250, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 30)
  my_s249 <- NormalizeData(my_s249, normalization.method = "LogNormalize", scale.factor = 10000)
  my_s250 <- NormalizeData(my_s250, normalization.method = "LogNormalize", scale.factor = 10000)
  my_s249 = FindVariableFeatures(my_s249, selection.method = "vst", nfeatures = 2000)
  my_s250 = FindVariableFeatures(my_s250, selection.method = "vst", nfeatures = 2000)
  reference.list = c(my_s249,my_s250)
  sc<- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
  sc.integrated <- IntegrateData(anchorset = sc, dims = 1:30)
  DefaultAssay(sc.integrated) <- "integrated"
#############
Then I did "sc <- filterdata(sc,mintotal=1000,CGenes=rownames(x)[grep("^(mt|Rp(l|s)|Gm\d)",rownames(x))])". In your opinion, it seems I did not to do the seurat filter step, right?

My expData has 62 rows with followed data:
![image](https://user-images.githubusercontent.com/25957174/92382934-0ad2a780-f140-11ea-82b1-b6361afdc6c1.png)

Thanks!

**Comment by dgrun** [comment]
62 features is very little. I would run the filterdata function on a count
matrix with all genes.

**Comment by skytguuu** [comment]
Do you mean that I should not filter data with seurat firstly? Because I used seurat pipeline firstly, including the feature selection, I thought maybe this step lead to the less features.

**Comment by dgrun** [comment]
You can work with the cells you obtained after Seurat filtering, but I
would not filter genes.

**Comment by skytguuu** [comment]
As your advise, I tried again. However, I firstly obtained cells after Seurat filtering, and did not filter the genes with (filterdata). Followed is my code:

###############
s249 = read.csv("SC249.csv",header=TRUE, row.names=1,stringsAsFactors=FALSE)
s250 = read.csv("SC250.csv",header=TRUE, row.names=1,stringsAsFactors=FALSE)
my_s249 <- CreateSeuratObject(counts = s249,min.cells = 3, min.features = 200,project = "sc_project")
my_s250 <- CreateSeuratObject(counts = s250,min.cells = 3, min.features = 200,project = "sc_project")
my_s249[["percent.mt"]]=PercentageFeatureSet(my_s249, pattern = "^mt.")
my_s250[["percent.mt"]]=PercentageFeatureSet(my_s250, pattern = "^mt.")
my_s249 <- subset(my_s249, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 30)
my_s250 <- subset(my_s250, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 30)
my_s249 <- NormalizeData(my_s249, normalization.method = "LogNormalize", scale.factor = 10000)
my_s250 <- NormalizeData(my_s250, normalization.method = "LogNormalize", scale.factor = 10000)
my_s249 = FindVariableFeatures(my_s249, selection.method = "vst", nfeatures = 2000)
my_s250 = FindVariableFeatures(my_s250, selection.method = "vst", nfeatures = 2000)
reference.list = c(my_s249,my_s250)
sc<- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
sc.integrated <- IntegrateData(anchorset = sc, dims = 1:30)
DefaultAssay(sc.integrated) <- "integrated"
sc <- SCseq(x)
expData <- getExpData(sc)
res <- pruneKnn(expData,no_cores=5)
#############
But when I tried expData, I found there is nothing in expData, and got the same error with pruneKnn. 
I don't whether my understanding is right or not?

Thanks for your help!

**Comment by dgrun** [comment]
you still have to execute the filterdata function after initialization:
sc <- SCseq(x)
sc <- filterdata(sc,mintotal=1)

Set mintotal to something small to avoid additional filtering of the
Seurat-filtered matrix.

**Comment by skytguuu** [comment]
Unfortunately, I failed again. I set the parameter with mintotal=1, but the nrow of expData is only 87. So, I got the same error. 
Then, btw, I tried to use raceid to filter without the seurat pipeline. However, I found my two batch datasets have different rows (genes), so how can I remove the batch effect with the different number of rows datasets?

Thanks!

**Comment by dgrun** [comment]
Sorry, but this is difficult for me to understand. I can only help if you
could provide example code with example data in order to reproduce the
problem.
Thanks!

**Comment by skytguuu** [comment]
I am appreciated for your patiently help. The problem was fixed by not findviablefeatures of seurat.  
I have another question about this tools. I tried subset a cell population (684 cells) from seurat and try to use this cell population to run raceid. I am not sure whether this processure is reasonable or not?
Thanks!
Best

**Comment by dgrun** [comment]
Glad, it worked for you.
Yes, sure it is reasonable. You should subset the input to RaceID, and
avoid further cell filtering with the filterdata function, e.g., by setting
mintotal=1.

**Comment by skytguuu** [comment]
Thanks for your explaination. When I tried the clustexp function, I got an error that: "Error in clusGapExt(diM[n, n], FUNcluster = function(x, k) cluster::pam(as.dist(x),  : length(dim(x)) == 2 is not TRUE". Becuase this data has a small cells, so I used normal pipeline of raceid. My code is:
#########################
d = as.matrix(seurat_out@assays$RNA@data)
 sc <- filterdata(sc,mintotal=1,CGenes=NULL)
 fdata <- getfdata(sc)
 sc <- compdist(sc,metric="pearson")
 sc <- clustexp(sc)
###############

**Comment by dgrun** [comment]
Sorry, but I don't understand the problem without having a look at sample
data...

**Comment by skytguuu** [comment]
The matrix d is ：
![image](https://user-images.githubusercontent.com/25957174/92707533-f385fb00-f387-11ea-942b-5ea66e932ff5.png)
and the sc data is ：
![image](https://user-images.githubusercontent.com/25957174/92707674-0f899c80-f388-11ea-8e6c-833b4a6c525d.png)
![image](https://user-images.githubusercontent.com/25957174/92707732-1dd7b880-f388-11ea-9d27-f05b1517542f.png)
![image](https://user-images.githubusercontent.com/25957174/92707770-262ff380-f388-11ea-8f7f-40130b255721.png)

**Comment by dgrun** [comment]
Well, you need to attach the matrix as a file for me to reproduce your error...

**Comment by skytguuu** [comment]
I have uploaded my rds data on "https://github.com/skytguuu/test/test.rds". Could you help me to figure out the problem? 
Thank you very much!
Best

**Comment by dgrun** [comment]
The gene filtering was too strong. I just changed the parameters...

sc <- filterdata(sc,mintotal=1,CGenes=NULL,minexpr=1,minnumber=1)


For me everything works then.

**Comment by skytguuu** [comment]
Thanks for your help. According to your code, it worked. I found, if I used the code " sc <- filterdata(sc,mintotal=1,CGenes=NULL)", it will failed, but it worked when added the parameter "minexpr=1, minnumber=1". 

I am appreciated for your help.
Thanks!
Best
